//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class congViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public congViec()
        {
            this.tt_ungVien = new HashSet<tt_ungVien>();
        }
    
        public string maCongViec { get; set; }
        public string loaiCongViec { get; set; }
        public string tenCongViec { get; set; }
        public Nullable<int> thoiGian { get; set; }
        public Nullable<decimal> mucLuong { get; set; }
        public string maTrinhDo { get; set; }
    
        public virtual trinhDo trinhDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_ungVien> tt_ungVien { get; set; }
    }
}
