//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diaChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diaChi()
        {
            this.tt_tuyenDung = new HashSet<tt_tuyenDung>();
            this.tt_ungVien = new HashSet<tt_ungVien>();
        }
    
        public string maDiaChi { get; set; }
        public string tinh { get; set; }
        public string thanhPho { get; set; }
        public string huyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_tuyenDung> tt_tuyenDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_ungVien> tt_ungVien { get; set; }
    }
}
