//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kyNang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kyNang()
        {
            this.trinhDo = new HashSet<trinhDo>();
        }
    
        public string maKyNang { get; set; }
        public Nullable<int> dienDat { get; set; }
        public Nullable<int> giaiQuyetVanDe { get; set; }
        public Nullable<int> sangTao { get; set; }
        public Nullable<int> hoaDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trinhDo> trinhDo { get; set; }
    }
}
