//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class job_suppbortEntities : DbContext
    {
        public job_suppbortEntities()
            : base("name=job_suppbortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<congViec> congViec { get; set; }
        public virtual DbSet<diaChi> diaChi { get; set; }
        public virtual DbSet<kyNang> kyNang { get; set; }
        public virtual DbSet<ngoaiNgu> ngoaiNgu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tinhTrang_TD> tinhTrang_TD { get; set; }
        public virtual DbSet<tt_tuyenDung> tt_tuyenDung { get; set; }
        public virtual DbSet<tt_ungVien> tt_ungVien { get; set; }
        public virtual DbSet<trinhDo> trinhDo { get; set; }
        public virtual DbSet<taiKhoan_DN> taiKhoan_DN { get; set; }
        public virtual DbSet<taiKhoan_UV> taiKhoan_UV { get; set; }
    }
}
