//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngoaiNgu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ngoaiNgu()
        {
            this.trinhDo = new HashSet<trinhDo>();
        }
    
        public string maNgoaiNgu { get; set; }
        public string tenNgoaiNgu { get; set; }
        public Nullable<int> nghe { get; set; }
        public Nullable<int> noi { get; set; }
        public Nullable<int> doc { get; set; }
        public Nullable<int> viet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trinhDo> trinhDo { get; set; }
    }
}
