//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tinhTrang_TD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tinhTrang_TD()
        {
            this.tt_tuyenDung = new HashSet<tt_tuyenDung>();
        }
    
        public string maTinhTrang { get; set; }
        public string trangThai { get; set; }
        public Nullable<int> soLuongCanTuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_tuyenDung> tt_tuyenDung { get; set; }
    }
}
