//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trinhDo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trinhDo()
        {
            this.congViec = new HashSet<congViec>();
            this.tt_tuyenDung = new HashSet<tt_tuyenDung>();
        }
    
        public string maTrinhDo { get; set; }
        public string totNghiepTruong { get; set; }
        public string nganhHoc { get; set; }
        public string chuyenNganh { get; set; }
        public Nullable<int> kinhNghiemLV { get; set; }
        public string moTa { get; set; }
        public string maNgoaiNgu { get; set; }
        public string maKyNang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<congViec> congViec { get; set; }
        public virtual kyNang kyNang { get; set; }
        public virtual ngoaiNgu ngoaiNgu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_tuyenDung> tt_tuyenDung { get; set; }
    }
}
