//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_tuyenDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_tuyenDung()
        {
            this.taiKhoan_DN = new HashSet<taiKhoan_DN>();
        }
    
        public string ID_doanhNghiep { get; set; }
        public string loaiHinhHD { get; set; }
        public string thuocVe { get; set; }
        public string maTinhDo { get; set; }
        public string veDoanhNghiep { get; set; }
        public string gmail { get; set; }
        public int SDT { get; set; }
        public string maDiaCHi { get; set; }
        public string maTinhTrang { get; set; }
    
        public virtual diaChi diaChi { get; set; }
        public virtual tinhTrang_TD tinhTrang_TD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taiKhoan_DN> taiKhoan_DN { get; set; }
        public virtual trinhDo trinhDo { get; set; }
    }
}
