//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_sp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_ungVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_ungVien()
        {
            this.taiKhoan_UV = new HashSet<taiKhoan_UV>();
        }
    
        public string ID { get; set; }
        public string tenUV { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string gmail { get; set; }
        public int SDT { get; set; }
        public string ghiChu { get; set; }
        public string trangThai { get; set; }
        public string maCongViec { get; set; }
        public string maDiaChi { get; set; }
    
        public virtual congViec congViec { get; set; }
        public virtual diaChi diaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taiKhoan_UV> taiKhoan_UV { get; set; }
    }
}
